#default -> local
spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  batch:
    job:
      names: ${job.name:NONE}
#      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
#    url: jdbc:postgresql://localhost:5432/batch_test
#    username: jaehyuklee
#    password:
#    driver-class-name: org.postgresql.Driver
    hikari:
      main-datasource:
        jdbc-url: jdbc:postgresql://localhost:5432/batch_test
        username: jaehyuklee
        password:
        driver-class-name: org.postgresql.Driver
      external-datasource:
        username: jaehyuklee
        password:
        driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: spring_batch
    hibernate:
      ddl-auto: update
---
spring:
  config:
    activate:
      on-profile: test
  jpa:
    database: h2

